const citation = {
    Citations: [
        {
            Auteur: "Confucius",
            hisCitations: [
                "Exige beaucoup de toi-même et attends peu des autres. Ainsi beaucoup d'ennuis te seront épargnés.",
                "Choisissez un travail que vous aimez et vous n'aurez pas à travailler un seul jour de votre vie.",
                "Trois sortes d'amis sont utiles, trois sortes d'amis sont néfastes. Les utiles : un ami droit, un ami fidèle, un ami cultivé. Les néfastes : un ami faux, un ami mou, un ami bavard.",
                "La nature fait les hommes semblables, la vie les rend différents.",
                "Agis avec gentillesse, mais n'attends pas de la reconnaissance.",
                "Lorsque l'on se cogne la tête contre un pot et que cela sonne creux, ça n'est pas forcément le pot qui est vide.",
                "Sous un bon gouvernement, la pauvreté est une honte ; sous un mauvais gouvernement, la richesse est aussi une honte.",
                "Je ne cherche pas à connaître les réponses, je cherche à comprendre les questions.",
                "Notre plus grande gloire n'est point de tomber, mais de savoir nous relever chaque fois que nous tombons.",
                "Nulle pierre ne peut être polie sans friction, nul homme ne peut parfaire son expérience sans épreuve.",
                "Pas trop d'isolement ; pas trop de relations ; le juste milieu, voilà la sagesse.",
                "L'homme de bien ne demande rien qu'à lui-même ; l'homme de peu demande tout aux autres.",
                "Examine si ce que tu promets est juste et possible, car la promesse est une dette.",
                "Si tu rencontres un homme de valeur, cherche à lui ressembler. Si tu rencontres un homme médiocre, cherche ses défauts en toi-même.",
                "Ne vous souciez pas de n'être pas remarqué ; cherchez plutôt à faire quelque chose de remarquable.",
                "Nous sommes frères par la nature, mais étrangers par l'éducation.",
                "L'expérience est une lanterne attachée dans notre dos, qui n'éclaire que le chemin parcouru.",
                "Celui qui ne progresse pas chaque jour, recule chaque jour.",
                "La conscience est la lumière de l'intelligence pour distinguer le bien du mal.",
                "Quand un homme a faim, mieux vaut lui apprendre à pêcher que de lui donner un poisson.",
                "Quand on ne sait pas ce qu'est la vie, comment pourrait-on savoir ce qu'est la mort ?",
                "Une petite impatience ruine un grand projet.",
                "Que l'on s'efforce d'être pleinement humain et il n'y aura plus de place pour le mal.",
                "Ne vous souciez pas d'être sans emploi ; souciez-vous plutôt d'être digne d'un emploi.",
                "Il faut se garder de trois fautes : parler sans y être invité, ce qui est impertinence ; ne pas parler quand on y est invité, ce qui est de la dissimulation ; parler sans observer les réactions de l'autre, ce qui est de l'aveuglement.",
                "J'entends et j'oublie, Je vois et je me souviens, Je fais et je comprends.",
                "Celui qui aime à apprendre est bien près du savoir.",
                "Le père qui n'enseigne pas ses devoirs à son fils est autant coupable que ce dernier s'il les néglige.",
                "Le sage est calme et serein. L'homme de peu est toujours accablé de soucis.",
                "La vraie faute est celle qu'on ne corrige pas.",
                "La vie de l'homme dépend de sa volonté ; sans volonté, elle serait abandonnée au hasard.",
                "Homme & Paroles",
                "L'homme supérieur c'est celui qui d'abord met ses paroles en pratique, et ensuite parle conformément à ses actions.",
                "Ne te crois point si important que les autres te paraissent insignifiants.",
                "L'expérience est une bougie qui n'éclaire que celui qui la porte.",
                "Celui qui déplace la montagne, c'est celui qui commence à enlever les petites pierres.",
                "Apprendre sans réfléchir est vain. Réfléchir sans apprendre est dangereux.",
                "Ne parlez jamais de vous, ni en bien, car on ne vous croirait pas, ni en mal car on ne vous croirait que trop.",
                "On doit aimer son prochain comme soi-même ; ne pas lui faire ce que nous ne voudrions pas qu'il nous fît.",
                "Le sage a honte de ses défauts, mais n'a pas honte de s'en corriger.",
                "Le problème des hommes, c'est qu'ils négligent leur propre champ pour aller ensemencer celui des autres.",
                "Rappelle-toi que ton fils n'est pas ton fils, mais le fils de son temps.",
                "Ecoutez beaucoup, afin de diminuer vos doutes ; soyez attentifs à ce que vous dites, afin de ne rien dire de superflu ; alors, vous commettrez rarement des fautes.",
                "Plutôt que de maudire les ténèbres, allumons une chandelle, si petite soit-elle.",
                "Sans principes communs, ce n'est pas la peine de discuter.",
                "L'homme de bien est droit et juste, mais non raide et inflexible ; il sait se plier mais pas se courber.",
                "La joie est en tout ; il faut savoir l'extraire.",
                "Celui qui sait obéir saura ensuite commander.",
                "Agissez envers les autres comme vous aimeriez qu'ils agissent envers vous.",
                "L'homme supérieur ne demande rien qu'à lui-même ; l'homme vulgaire et sans mérite demande tout aux autres.",
                "L'archer a un point commun avec l'homme de bien : quand sa flèche n'atteint pas le centre de la cible, il en cherche la cause en lui-même.",
                "Rien n'est jamais sans conséquence. En conséquence, rien n'est jamais gratuit.",
                "Rendez le bien pour le bien et la justice pour le mal.",
                "Le grave défaut est d'avoir des défauts et de ne pas s'efforcer de s'en corriger.",
                "Quiconque a entendu les cris d'un animal qu'on tue ne peut plus jamais manger de sa chair.",
                "Une image vaut mille mots.",
                "On peut connaître la vertu d'un homme en observant ses défauts.",
                "Veux-tu apprendre à bien vivre, apprends auparavant à bien mourir.",
                "Se regarder scrupuleusement soi-même, ne regarder que discrètement les autres.",
                "Qui ne se préoccupe pas de l'avenir lointain, se condamne aux soucis immédiats.",
                "Rien ne sert de parler des choses qui sont déjà accomplies, ni de faire des remontrances sur celles qui sont déjà très avancées, ni de blâmer ce qui est passé.",
                "Ce qu'on sait, savoir qu'on le sait ; ce qu'on ne sait pas, savoir qu'on ne le sait pas : c'est savoir véritablement.",
                "On s'égare rarement en s'imposant soi-même des règles sévères.",
                "Ne choisis tes amis que parmi tes égaux.",
                "Ne vous affligez pas de ce que les hommes ne vous connaissent pas ; affligez-vous de ne pas connaître les hommes.",
                "Lorsque vous travaillez pour les autres, faites-le avec autant d'ardeur que si c'était pour vous-même.",
                "Faire le bien sans chercher de récompense ; fuir le mal sans craindre le châtiment : homme rare sous le ciel.",
                "Lorsque les mots perdent leur sens, les gens perdent leur liberté.",
                "Entendre ou lire sans réfléchir est une occupation vaine ; réfléchir sans livre ni maître est dangereux.",
                "Le sage se demande à lui-même la cause de ses fautes, l'insensé le demande aux autres.",
                "Je ne peux rien pour qui ne se pose pas de questions.",
                "Le silence est un ami qui ne trahit jamais.",
                "L'homme honorable commence par appliquer ce qu'il veut enseigner ; ensuite il enseigne.",
                "Dépasser le but, ce n'est pas l'atteindre.",
                "Celui qui est sévère envers lui-même et indulgent envers les autres évite les mécontentements.",
                "Quand vous rencontrez un homme vertueux, cherchez à l'égaler. Quand vous rencontrez un homme dénué de vertu, examinez vos propres manquements.",
                "L'homme de bien situe la justice au-dessus de tout. Un homme de bien qui a la bravoure mais qui ignore la justice sera un rebelle. L'homme médiocre qui a la bravoure mais qui ignore la justice sera un brigand.",
                "Quand vous plantez une graine une fois, vous obtenez une seule et unique récolte. Quand vous instruisez les gens, vous en obtenez cent.",
                "Pour un mot, un homme est réputé sage ; pour un mot, un homme est jugé sot.",]

        },
        {
            Auteur: "Victor Hugo",
            hisCitations: [
                "On passe une moitié de sa vie à attendre ceux qu'on aimera et l'autre moitié à quitter ceux qu'on aime.",
                "On ne souffre jamais que du mal que nous font ceux qu'on aime. Le mal qui vient d'un ennemi ne compte pas.",
                "Enfer chrétien, du feu. Enfer païen, du feu. Enfer mahométan, du feu. Enfer hindou, des flammes. A en croire les religions, Dieu est né rôtisseur.",
                "Mieux vaut une conscience tranquille qu'une destinée prospère. J'aime mieux un bon sommeil qu'un bon lit.",
                "Le bonheur est parfois caché dans l'inconnu.",
                "L'éducation, c'est la famille qui la donne ; l'instruction, c'est l'Etat qui la doit.",
                "Une femme qu'on aime est toute une famille.",
                "La véritable indulgence consiste à comprendre et à pardonner les fautes qu'on ne serait pas capable de commettre.",
                "Mes amis, retenez ceci, il n'y a ni mauvaises herbes ni mauvais hommes. Il n'y a que de mauvais cultivateurs.",
                "Je crois ce que je dis, je fais ce que je crois.",
                "Il y a souvent plus de choses naufragées au fond d'une âme qu'au fond de la mer.",
                "Rien n'est stupide comme vaincre ; la vraie gloire est convaincre.",
                "La liberté commence où l'ignorance finit.",
                "Quand je suis triste, je pense à vous, comme l'hiver on pense au soleil, et quand je suis gai, je pense à vous, comme en plein soleil on pense à l'ombre.",
                "Lire, c'est boire et manger. L'esprit qui ne lit pas maigrit comme le corps qui ne mange pas.",
                "Une femme qui a un amant est un ange, une femme qui a deux amants est un monstre, une femme qui a trois amants est une femme.",
                "Quand le peuple sera intelligent, alors seulement le peuple sera souverain.",
                "N'imitez rien ni personne. Un lion qui copie un lion devient un singe.",
                "Ce n'est pas la chair qui est réel, c'est l'âme. La chair est cendre, l'âme est flamme.",
                "Les larmes sont un don. Souvent les pleurs, après l'erreur ou l'abandon, Raniment nos forces brisées.",
                "Ceux qui vivent sont ceux qui luttent.",
                "Et de l'union des libertés dans la fraternité des peuples naîtra la sympathie des âmes, germe de cet immense avenir où commencera pour le genre humain la vie universelle et que l'on appellera la paix.",
                "La musique [...] est la vapeur de l'art. Elle est à la poésie ce que la rêverie est à la pensée, ce que le fluide est au liquide, ce que l'océan des nuées est à l'océan des ondes.",
                "Un hypocrite est un patient dans la double acceptation du mot ; il calcule un triomphe et endure un supplice.",
                "Un sot est un imbécile dont on voit l'orgueil à travers les trous de son intelligence.",
                "Chaque homme dans sa nuit s'en va vers sa lumière.",
                "On est stupéfait de la quantité de critique que peut contenir un imbécile.",
                "Faire rire, c'est faire oublier. Quel bienfaiteur sur la terre, qu'un distributeur d'oubli !",
                "L'enfer est tout entier dans ce mot : solitude.",
                "Voici comment le problème du mariage est posé : le mari attend et veut la paix, le calme plat et l'épuisement ; la femme rêve les émotions du commencement, les joies de l'âme, le mois d'avril, l'aube ! l'un veut dormir, l'autre s'éveille.",
                "Il faut que je me défasse de la mauvaise habitude de vouloir toujours être écouté.",
                "La naïveté est le visage de la vérité.",
                "Il y a des gens qui vous laissent tomber un pot de fleurs sur la tête d'un cinquième étage et qui vous disent : je vous offre ces roses.",
                "Les enfants ont la mémoire courte, mais ils ont le souvenir rapide.",
                "Le jeune homme est beau, mais le vieillard est grand.",
                "Un petit peuple libre est plus grand qu'un grand peuple esclave.",
                "Le plus excellent symbole du peuple, c'est le pavé. On marche dessus jusqu'à ce qu'il vous tombe sur la tête.",
                "La vérité est comme le soleil. Elle fait tout voir et ne se laisse pas regarder.",
                "La confiance en soi fait le sot ; la foi en soi fait le grand homme.",
                "Rêver, c'est le bonheur ; attendre, c'est la vie.",
                "La mélancolie, c'est le bonheur d'être triste.",
                "La musique, c'est du bruit qui pense.",
                "La pensée est plus qu'un droit, c'est le souffle même de l'homme.",
                "Ma vie se résume en deux mots : Solitaire - Solidaire.",
                "Et l'on reconnaîtra que, même au point de vue de notre égoïsme, il est difficile de composer le bonheur de l'homme avec la souffrance de la femme.",
                "C'est une des choses les plus difficiles et les plus nécessaires de la vie que d'apprendre à dédaigner. Le dédain protège et écrase. C'est une cuirasse et une massue.",
                "Réfléchis longuement avant de te faire applaudir par tes ennemis.",
                "La mer est un espace de rigueur et de liberté.",
                "On résiste à l'invasion des armées, on ne résiste pas à l'invasion des idées.",
                "Qu'est-ce qu'un fleuve sans sa source ? Qu'est-ce qu'un peuple sans son passé ?",
                "Qui de bonne heure est vieux restera longtemps jeune.",
                "L'âme a des illusions comme l'oiseau a des ailes ; c'est ce qui la soutient.",
                "Les hommes chassent, les femmes pèchent.",
                "Aucune grâce extérieure n'est complète si la beauté intérieure ne la vivifie. La beauté de l'âme se répand comme une lumière mystérieuse sur la beauté du corps.",
                "Si Louis XVI eût aboli la peine de mort, comme il avait aboli la torture, sa tête ne serait pas tombée.",
                "La moitié d'un ami, c'est la moitié d'un traître.",
                "Oh ! L'amour serait un bien suprême si l'on pouvait mourir de trop aimer !",
                "L'homme a reçu de la nature une clef avec laquelle il remonte sa femme toutes les vingt-quatre heures.",
                "La prière est la soeur tremblante de l'amour.",
                "Ce qui est honteux, c'est de changer d'opinion pour son intérêt et que ce soit un écu ou un galon qui vous fasse brusquement passer du blanc au tricolore, et vice versa.",
                "L'athée dresse contre Dieu un Procès-verbal de carence.",
                "Tout bruit écouté longtemps devient une voix.",
                "La femme a une puissance singulière qui se compose de la réalité de la force et de l'apparence de la faiblesse.",
                "La vie est une phrase interrompue.",
                "La vraie et grande éloquence est celle dans laquelle, même aux moments calmes, on sent le grondement d'une foudre.",
                "Vous m'offrez la cité... je préfère les bois, car je trouve, voyant les hommes que vous êtes, plus de coeur aux rochers, moins de bêtise aux bêtes.",
                "Ne vous croyez ni grand ni petit ! Contemplez.",
                "Ainsi la paresse est mère. Elle a un fils, le vol, et une fille, la faim.",
                "Chaque enfant qu'on enseigne est un homme qu'on gagne. L'ignorance est la nuit qui commence l'abîme.",
                "Ne rien faire est le bonheur des enfants et le malheur des vieux.",
                "Remplacer la pensée par la rêverie, c'est confondre un poison avec une nourriture.",
                "Le devoir a une grande ressemblance avec le bonheur d'autrui.",
                "Il est effrayant de penser que cette chose qu'on a en soi, le jugement, n'est pas la justice. Le jugement, c'est le relatif. La justice, c'est l'absolu. Réfléchissez à la différence entre un juge et juste.",
                "Non, l'avenir n'est à personne ! Sire, l'avenir est à Dieu ! A chaque fois que l'heure sonne, Tout ici-bas nous dit adieu.",
                "Au fond, Dieu veut que l'homme désobéisse. Désobéir, c'est chercher.",
                "Le plus lourd fardeau, c'est d'exister sans vivre.",
                "De quelque mot profond tout homme est le disciple.",
                "Les plus petits esprits ont les plus gros préjugés.",
                "Sous la forme imprimerie, la pensée est plus impérissable que jamais ; elle est volatile, insaisissable, indestructible.",
                "Celui qui ouvre une porte d'école, ferme une prison.",
                "La rumeur est la fumée du bruit.",
                `Dans "connaître", il y a "naître".`,
                "La vie, le malheur, l'isolement, l'abandon, la pauvreté, sont des champs de bataille qui ont leurs héros ; héros obscurs plus grands parfois que les héros illustres.",
                "L'homme c'est l'impuissant fécondant l'inutile.",
                "Le premier des bons ménages est celui qu'on fait avec sa conscience.",
                "Dieu a inventé le chat pour que l'homme ait un tigre à caresser chez lui.",
                "L'affection réciproque n'a pas ce degré de sensibilité ardente qui fait que le moindre pli est un supplice. Les vieux amis s'aiment avec des plis.",
                "Chose inouïe, c'est au-dedans de soi qu'il faut regarder le dehors.",
                "Il est toujours bon d'être bon.",
                "L'âme est le seul oiseau qui soutienne sa cage.",
                "C'est une chose étrange à quel point la sécurité de la conscience donne la sécurité du reste.",
                "Dis-moi qui tu aimes, je te dirai qui tu es.",
                "Il y a du consentement dans le sourire, tandis que le rire est souvent un refus.",
                "L'amour d'une famille, le centre autour duquel tout gravite et tout brille.",
                ]
        },
        {
            Auteur: "Albert Einstein",
            hisCitations: [
                "Le monde est dangereux à vivre ! Non pas tant à cause de ceux qui font le mal, mais à cause de ceux qui regardent et laissent faire.",
                "La vie, c'est comme une bicyclette, il faut avancer pour ne pas perdre l'équilibre.",
                "Il n'existe que deux choses infinies, l'univers et la bêtise humaine... mais pour l'univers, je n'ai pas de certitude absolue.",
                "Placez votre main sur un poêle une minute et ça vous semble durer une heure. Asseyez vous auprès d'une jolie fille une heure et ça vous semble durer une minute. C'est ça la relativité.",
                "La valeur d'un homme tient dans sa capacité à donner et non dans sa capacité à recevoir.",
                "Le monde ne sera pas détruit par ceux qui font le mal, mais par ceux qui les regardent sans rien faire.",
                "N'essayez pas de devenir un homme qui a du succès. Essayez de devenir un homme qui a de la valeur.",
                "Soit A un succès dans la vie. Alors A = x + y + z, où x = travailler, y = s'amuser, z = se taire.",
                "La connaissance s'acquiert par l'expérience, tout le reste n'est que de l'information.",
                "Le mot progrès n'aura aucun sens tant qu'il y aura des enfants malheureux.",
                "Je ne sais pas comment sera la troisième guerre mondiale, mais je sais qu'il n'y aura plus beaucoup de monde pour voir la quatrième.",
                "La folie, c'est se comporter de la même manière et s'attendre à un résultat différent.",
                "Les grands esprits ont toujours rencontré une opposition farouche des esprits médiocres.",
                "Il n'y a que deux façons de vivre sa vie : l'une en faisant comme si rien n'était un miracle, l'autre en faisant comme si tout était un miracle.",
                "Le hasard, c'est Dieu qui se promène incognito.",
                "Il est plus facile de désintégrer un atome qu'un préjugé.",
                "Une personne qui n'a jamais commis d'erreurs n'a jamais tenté d'innover.",
                "Un problème créé ne peut être résolu en réfléchissant de la même manière qu'il a été créé.",
                "L'imagination est plus importante que le savoir.",
                "Que chacun raisonne en son âme et conscience, qu'il se fasse une idée fondée sur ses propres lectures et non d'après les racontars des autres.",
                "Ce qui compte ne peut pas toujours être compté, et ce qui peut être compté ne compte pas forcément.",
                "Ceux qui aiment marcher en rangs sur une musique : ce ne peut être que par erreur qu'ils ont reçu un cerveau, une moelle épinière leur suffirait amplement.",
                "L'Etat est notre serviteur et nous n'avons pas à en être les esclaves.",
                "Il est hélas devenu évident aujourd'hui que notre technologie a dépassé notre humanité.",
                "C'est la personne humaine, libre et créatrice qui façonne le beau et le sublime, alors que les masses restent entraînées dans une ronde infernale d'imbécillité et d'abrutissement.",
                "Pour être un membre irréprochable parmi une communauté de moutons, il faut avant toute chose être soi-même un mouton.",
                "L'enseignement devrait être ainsi : celui qui le reçoit le recueille comme un don inestimable mais jamais comme une contrainte pénible.",
                "Ne fais jamais rien contre ta conscience, même si ceux qui se pensent t'être supèrieure te le demande.",
                "Ce qui fait la vraie valeur d'un être humain, c'est de s'être délivré de son petit moi.",
                "Un problème sans solution est un problème mal posé.",
                "Ce n'est pas à cause de l'attraction terrestre que des gens tombent... amoureux !",
                "Rare est le nombre de ceux qui regardent avec leurs propres yeux et qui éprouvent avec leur propre sensibilité.",
                "C'est le devoir de chaque homme de rendre au monde au moins autant qu'il en a reçu.",
                "Le progrès technique est comme une hache qu'on aurait mis dans les mains d'un psychopathe.",
                "L'école devrait toujours avoir pour but de donner à ses élèves une personnalité harmonieuse, et non de les former en spécialiste.",
                "Peu d'être sont capables d'exprimer posément une opinion différente des préjugés de leur milieu. La plupart des êtres sont mêmes incapables d'arriver à formuler de telles opinions.",
                "Le mental intuitif est un don sacré et le mental rationnel est un serviteur fidèle. Nous avons créé une société qui honore le serviteur et a oublié le don.",
                "Je ne crois point, au sens philosophique du terme, à la liberté de l'homme. Chacun agit non seulement sous une contrainte extérieure, mais aussi d'après une nécessité intérieure.",
                "Le monde que nous avons créé est le résultat de notre niveau de réflexion, mais les problèmes qu'il engendre ne sauraient être résolus à ce même niveau.",
                "La chose la plus difficile à comprendre au monde c'est l'impôt sur le revenu !",
                "Je ne pense jamais au futur. Il vient bien assez tôt.",
                "Le plus beau sentiment du monde, c'est le sens du mystère. Celui qui n'a jamais connu cette émotion, ses yeux sont fermés.",
                "Nous aurons le destin que nous aurons mérité.",
                "La vraie valeur d'un homme se détermine en examinant dans quelle mesure et dans quel sens il est parvenu à se libérer du moi.",
                "Rien ne peut être aussi bénéfique à la santé humaine et augmenter les chances de survie de la vie sur terre que d'opter pour une diète végétarienne.",
                "Si vous ne pouvez expliquer un concept à un enfant de six ans, c'est que vous ne le comprenez pas complètement.",
                "Rien n'est plus proche du vrai que le faux.",
                "La seule chose absolue dans un monde comme le nôtre, c'est l'humour.",
                "Si l'idée n'est pas à priori absurde, elle est sans espoir.",
                "Ce qui m'intéresse vraiment c'est de savoir si Dieu avait un quelconque choix en créant le monde.",
                "La distinction entre le passé, le présent, le futur n'est qu'une illusion, aussi tenace soit-elle.",
                "La science sans religion est boiteuse, la religion sans science est aveugle.",
                "La science sans religion est boiteuse, la religion sans science est aveugle.",
                "La plus belle chose que nous puissions éprouver, c'est le côté mystérieux de la vie.",
                "Les machines un jour pourront résoudre tous les problèmes, mais jamais aucune d'entre elles ne pourra en poser un !",
                "Je ne dors pas longtemps, mais je dors vite.",
                "Le problème aujourd'hui n'est pas l'énergie atomique, mais le coeur des hommes.",
                "Celui qui ne peut plus éprouver ni étonnement ni surprise, est pour ainsi dire mort : ses yeux sont éteints.",
                "J'affirme que le sentiment religieux cosmique est le motif le plus puissant et le plus noble de la recherche scientifique.",
                "C'est le rôle essentiel du professeur d'éveiller la joie de travailler et de connaître.",
                "L'escalier de la science est l'échelle de Jacob, il ne s'achève qu'aux pieds de Dieu.",
                "Les amères leçons du passé doivent être réapprises sans cesse.",
                "La vie est une aventure, elle doit être sans cesse disputée à la mort.",
                "Je veux connaître les pensées de Dieu ; tout le reste n'est que détail.",
                "Définissez-moi d'abord ce que vous entendez par Dieu et je vous dirai si j'y crois.",
                "J'aime penser que la lune est là même si je ne la regarde pas.",
            ]
        },
        {
            Auteur: "Mahatma Gandhi",
            hisCitations: [
                "La vie est un mystère qu'il faut vivre, et non un problème à résoudre.",
                "La règle d'or de la conduite est la tolérance mutuelle, car nous ne penserons jamais tous de la même façon, nous ne verrons qu'une partie de la vérité et sous des angles différents.",
                "Si la non-violence est la loi de l'humanité, l'avenir appartient aux femmes. Qui peut faire appel au coeur des hommes avec plus d'efficacité que la femme ?",
                "La victoire obtenue par la violence équivaut à une défaite, car elle est momentanée.",
                "La non-violence est infiniment supérieure à la violence, le pardon est plus viril que le châtiment. Le pardon est la parure du soldat.",
                "On ne peut battre son adversaire que par l'amour et non la haine. La haine est la forme la plus subtile de la violence. La haine blesse celui qui hait, et non le haï.",
                "La vie sans religion est une vie sans principe, et une vie sans principe est comme un bateau sans gouvernail.",
                "Je m'oppose à la violence parce que lorsqu'elle semble produire le bien, le bien qui en résulte n'est que transitoire, tandis que le mal produit est permanent.",
                "La haine tue toujours, l'amour ne meurt jamais.",
                "C'est une erreur de croire nécessairement faux ce qu'on ne comprend pas.",
                "Un homme cruel avec les animaux ne peut être un homme bon.",
                "Vis comme si tu devais mourir demain. Apprends comme si tu devais vivre toujours.",
                "Commencez par changer en vous ce que vous voulez changer autour de vous.",
                "Lorsque nous critiquons, il faut le faire avec une humilité et une courtoisie qui ne laisse subsister aucune amertume.",
                "On peut juger de la grandeur d'une nation par la façon dont les animaux y sont traités.",
                "Là où il n'y a le choix qu'entre lâcheté et violence, je conseillerai la violence.",
                "Vous devez être le changement que vous voulez voir dans ce monde.",
                "Chacun a raison de son propre point de vue, mais il n'est pas impossible que tout le monde ait tort.",
                "C'est dans l'effort que l'on trouve la satisfaction et non dans la réussite. Un plein effort est une pleine victoire.",
                "La véritable éducation consiste à tirer le meilleur de soi-même. Quel meilleur livre peut-il exister que le livre de l'humanité ?",
                "La démocratie devrait assurer au plus faible les mêmes opportunités qu'au plus fort.",
                "Dès que quelqu'un comprend qu'il est contraire à sa dignité d'homme d'obéir à des lois injustes, aucune tyrannie ne peut l'asservir.",
                "Il faut être fier d'avoir hérité de tout ce que le passé avait de meilleur et de plus noble. Il ne faut pas souiller son patrimoine en multipliant les erreurs passées.",
                "La vérité est dure comme le diamant et fragile comme la fleur de pêcher.",
                "Aucun pays ne s'est jamais élevé sans s'être purifié au feu de la souffrance.",
                "Si nous entretenons dans notre coeur la malice et la haine et que nous faisions semblant de ne pas vouloir la vengeance, celle-ci devra faire retour sur nous, et elle nous conduira à notre perte.",
                "Colère et intolérance sont les ennemis d'une bonne compréhension.",
                "La non-violence est la loi de notre espèce tout comme la violence est la loi de l'animal.",
                "Le coeur le plus endurci et l'ignorance la plus crasse doivent disparaître devant le soleil levant de la souffrance patiente et sans méchanceté.",
                "Tout compromis repose sur des concessions mutuelles, mais il ne saurait y avoir de concessions mutuelles lorsqu'il s'agit de principes fondamentaux.",
                "Un pas à la fois me suffit.",
                "Cultiver l'humilité revient à cultiver l'hypocrisie. L'humble n'a pas conscience de son humilité.",
                "Si chacun ne conservait que ce dont il a besoin, nul ne manquerait de rien, et chacun se contenterait de ce qu'il a.",
                "La force du nombre ne réjouit que le peureux. Celui qui est courageux en esprit se fait gloire de combattre seul.",
                "S'abstenir de punir n'est pardon que quand il existe le pouvoir de punir.",
                `Appeler les femmes "le sexe faible" est une diffamation ; c'est l'injustice de l'homme envers la femme. Si la non-violence est la loi de l'humanité, l'avenir appartient aux femmes.`,
                "La non-violence, sous sa forme active, consiste en une bienveillance envers tout ce qui existe. C'est l'amour pur.",
                "Il n'y aura jamais d'égalité tant qu'on se sent inférieur ou supérieur à autrui. Entre égaux il ne saurait y avoir de condescendance.",
                "Il n'y a pas d'au revoir pour nous. Peu importe où tu es, tu seras toujours dans mon coeur.",
                "La vraie moralité ne consiste pas à suivre les sentiers battus, mais à découvrir ce qui est pour nous-mêmes la vraie voie et à la suivre avec intrépidité. Tout véritable progrès est impossible sans une telle poursuite acharnée de la vérité.",
                "La non-violence ne consiste pas à renoncer à toute lutte réelle contre le mal. C'est au contraire, contre le mal, une lutte plus active et plus réelle que la loi du talion.",
                "Les systèmes économiques qui négligent les facteurs moraux et sentimentaux sont comme des statues de cire : ils ont l'air d'être vivants et pourtant il leur manque la vie de l'être en chair et en os.",
                "Vivre tous simplement pour que tous puissent simplement vivre.",
                `Je connais le chemin : il est étroit, comme le fil d'une épée. Je me réjouis si je parviens à le suivre. Je pleure si j'en dévie. Car Dieu nous dit : "Seul celui qui essaie de suivre le chemin ne périra jamais"...`,
                "En réalité il existe autant de religions que d'individus.",
                "Je n'aime pas le mot tolérance, mais je n'en trouve pas de meilleur.",
                "Il vaut mieux mettre son coeur dans la prière sans trouver de paroles que trouver des mots sans y mettre son coeur.",
                "Les masses affamées ne réclament qu'un seul poème : de la nourriture réconfortante. On ne doit pas la leur donner en aumône. Il faut qu'elles la gagnent à la sueur de leur front.",
                "Dieu ne t'apparaît pas en personne mais en action.",
                "Une vie de sacrifice est le sommet suprême de l'art. Elle est pleine d'une véritable joie.",
                "Croire en quelque chose et ne pas le vivre, c'est malhonnête.",
                "Le patriotisme n'est pas exclusif : c'est la même chose que l'humanité. Je suis patriote parce que je suis homme et humain.",
                "Etre en retard est un acte de violence.",
                "Moins on possède, moins on désire.",
                "Si Dieu devait apparaître aux affamés, il n'oserait leur apparaître que sous forme de nourriture.",
                "Jouis des choses de la terre en y renonçant.",
                "La loi de l'amour se montre plus efficace que ne l'a jamais été la loi de la destruction.",
                "Comment peut-on apprendre à se connaître soi-même ? Par la méditation, jamais, mais bien par l'action.",
                "Sans doute serais-je chrétien, si les chrétiens l'étaient vingt-quatre heures par jour.",
                "Le progrès spirituel exige de nous que nous cessions de tuer les autres êtres vivants pour nos besoins corporels.",
                "Le monde est fatigué de la haine.",
                "La non-violence est la loi de notre espèce comme la violence est la loi de la brute.",
                "Notre vie est une longue et pénible quête de la Vérité.",
                "Nul être humain n'est trop mauvais pour être sauvé. Nul être humain n'est assez parfait pour avoir le droit de tuer celui qu'il considère à tort comme entièrement mauvais.",
                "Ma vie est mon seul enseignement.",
                "Celui qui veut sacrifier sa vie pour autrui, n'a guère le temps de s'assurer une place au soleil.",
                "La civilisation ne consiste pas à multiplier les besoins mais à les réduire volontairement, délibérément. Cela seul amène le vrai bonheur.",
                "L'amour est ce qu'il y a de plus fort au monde, cependant on ne peut rien imaginer de plus humble.",
                "Il faut apprendre à rester serein au milieu de l'activité et à être vibrant de vie au repos.",
                "Les principes de la religion sont une chose, les pratiques qui les prennent pour base en sont une autre. Les principes sont absolument indépendants du temps et de l'espace. Les pratiques changent selon l'époque et selon le lieu.",
                "Le vrai démocrate est celui qui, par des moyens non violents, défend sa liberté, par conséquent celle de son pays, et finalement celle de l'humanité toute entière.",
                "L'erreur ne devient pas vérité parce qu'elle se propage et se multiplie ; la vérité ne devient pas erreur parce que nul ne la voit.",
                "La goutte d'eau séparée de l'océan peut trouver un repos momentané, mais celle qui est dans l'océan ne connaît pas de repos.",
                "Dès que nous perdons la base morale, nous cessons d'être religieux. La religion ne saurait renverser et supplanter la moralité.",
                "Que nous devions obéir à toutes les lois, qu'elles soient bonnes ou mauvaises, est une invention récente.",
                "Les religions sont comme des routes différentes convergeant vers un même point. Qu'importe que nous empruntions des voies différentes, pourvu que nous arrivions au même but.",
                "Donner un verre d'eau en échange d'un verre d'eau n'est rien ; la vraie grandeur consiste à rendre le bien pour le mal.",
                "Il y a assez de tout dans le monde pour satisfaire aux besoins de l'homme, mais pas assez pour assouvir son avidité.",
                "Le ciel et la terre sont en nous.",
                "Nul homme qui aime son pays ne peut l'aider à progresser s'il ose négliger le moindre de ses compatriotes.",
            ]
        },
        {
            Auteur: "Martin Luther King",
            hisCitations: [
                "La véritable grandeur d'un homme ne se mesure pas à des moments où il est à son aise, mais lorsqu'il traverse une période de controverses et de défis.",
                "Nous devons apprendre à vivre ensemble comme des frères, sinon nous allons mourir tous ensemble comme des idiots.",
                "Rien n'est plus dangereux au monde que la véritable ignorance et la stupidité consciencieuse.",
                "La haine trouble la vie ; l'amour la rend harmonieuse. La haine obscurcit la vie ; l'amour la rend lumineuse.",
                "La race humaine doit sortir des conflits en rejetant la vengeance, l'agression et l'esprit de revanche. Le moyen d'en sortir est l'amour.",
                "Ce qui m'effraie, ce n'est pas l'oppression des méchants ; c'est l'indifférence des bons.",
                "L'obscurité ne chasse pas l'obscurité, seule la lumière peut le faire.",
                "Chacun a la responsabilité morale de désobéir aux lois injustes.",
                "A la fin, nous nous souviendrons non pas des mots de nos ennemis, mais des silences de nos amis.",
                "Tout le monde peut être important car tout le monde peut servir à quelque chose.",
                "La non-violence est une arme puissante et juste, qui tranche sans blesser et ennoblit l'homme qui la manie. C'est une épée qui guérit.",
                "Une injustice commise quelque part est une menace pour la justice dans le monde entier.",
                "L'homme bon ne regarde pas les particularités physiques mais sait discerner ces qualités profondes qui rendent les gens humains, et donc frères.",
                "Tant qu'un homme n'a pas découvert quelque chose pour lequel il serait prêt à mourir, il n'est pas à même de vivre.",
                "Une nation qui produit de jour en jour des hommes stupides achète à crédit sa propre mort spirituelle.",
                "Notre pouvoir scientifique a dépassé notre pouvoir spirituel. Nous savons guider des missiles mais nous détournons l'homme de sa voie.",
                "Une loi ne pourra jamais obliger un homme à m'aimer mais il est important qu'elle lui interdise de me lyncher.",
                "Celui qui accepte le mal sans lutter contre lui coopère avec lui.",
                "Faites le premier pas sur le chemin de la foi. Vous n'avez pas à le parcourir entièrement, juste à faire le premier pas.",
                "J'ai le rêve qu'un jour mes quatre enfants vivront dans une nation où ils ne seront pas jugés pour la couleur de leur peau, mais pour leur caractère.",
                "Mieux vaut souffrir dans la dignité, qu'accepter la ségrégation dans l'humiliation.",
                "Dieu a les deux bras étendus. L'un est assez fort pour entourer de justice, l'autre assez doux pour nous entourer de grâce.",
                "Rien n'est plus tragique que de rencontrer un individu à bout de souffle, perdu dans le labyrinthe de la vie.",
                "Tout ce que nous voyons n'est qu'une ombre projetée par les choses que nous ne voyons pas.",
                "Un homme devrait faire son travail si parfaitement que les vivants, les morts, et ceux encore à naître ne puissent faire mieux.",
                "Ce n'est qu'en aimant nos ennemis que nous pouvons connaître Dieu et faire l'expérience de sa sainteté.",
                "Ce n'est pas nous qui faisons l'histoire. C'est l'histoire qui nous fait.",
                "La non-violence est la réponse aux cruciales questions politiques et morales de notre temps.",
                "Nous ne devons pas laisser notre protestation créatrice dégénérer en violence physique.",
                "Dieu n'est-il pas un extrémiste de l'amour ?",
                "Tous les progrès sont précaires, et la solution d'un problème nous confronte à un autre problème.",
                "Si la mort physique est le prix à payer pour libérer mes frères blancs d'une mort spirituelle irrévocable, rien ne peut être alors plus rédempteur.",
                "Les barricades sont les voix de ceux qu'on n'entend pas.",
                "Civilisation et violence sont des concepts antithétiques.",
            ]
        },
        {
            Auteur: "Nelson Mandela",
            hisCitations: [
                "L'honnêteté, la sincérité, la simplicité, l'humilité, la générosité, l'absence de vanité, la capacité à servir les autres - qualités à la portée de toutes les âmes- sont les véritables fondations de notre vie spirituelle.",
                "Etre libre, ce n'est pas seulement se débarrasser de ses chaînes ; c'est vivre d'une façon qui respecte et renforce la liberté des autres.",
                "J'ai appris que le courage n'est pas l'absence de peur, mais la capacité de la vaincre.",
                "L'éducation est l'arme la plus puissante qu'on puisse utiliser pour changer le monde.",
                "Nous travaillerons ensemble pour soutenir le courage là où il y a la peur, pour encourager la négociation là où il y a le conflit, et donner l'espoir là où règne le désespoir",
                "Je ne suis pas vraiment libre si je prive quelqu'un d'autre de sa liberté. L'opprimé et l'oppresseur sont tous deux dépossédés de leur humanité.",
                "Pour faire la paix avec un ennemi, on doit travailler avec cet ennemi, et cet ennemi devient votre associé.",
                "Tout homme ou institution qui essaiera de me voler ma dignité perdra.",
                "Aucun de nous, en agissant seul, ne peut atteindre le succès.",
                "Un combattant de la liberté apprend de façon brutale que c'est l'oppresseur qui définit la nature de la lutte, et il ne reste souvent à l'opprimé d'autre recours que d'utiliser les méthodes qui reflètent celles de l'oppresseur",
                "Nous ne sommes pas encore libres, nous avons seulement atteint la liberté d'être libres.",
                "Un homme qui prive un autre homme de sa liberté est prisonnier de la haine, des préjugés et de l'étroitesse d'esprit.",
                "En faisant scintiller notre lumière, nous offrons aux autres la possibilité d'en faire autant.",
                "N'oublie pas qu'un saint est un pêcheur qui cherche à s'améliorer.",
                "Que règne la liberté. Car jamais le soleil ne s'est couché sur réalisation humaine plus glorieuse.",
                "Les hommes qui prennent de grands risques doivent s'attendre à en supporter souvent les lourdes conséquences.",
            ]
        },
        {
            Auteur: "Voltaire",
            hisCitations: [
                "Le meilleur gouvernement est celui où il y a le moins d'hommes inutiles.",
                "On parle toujours mal quand on n'a rien à dire.",
                "Le travail éloigne de nous trois grands maux : l'ennui, le vice et le besoin.",
                "Dire le secret d'autrui est une trahison, dire le sien est une sottise.",
                "L'art de la médecine consiste à distraire le malade pendant que la nature le guérit.",
                "Le fanatisme est un monstre qui ose se dire le fils de la religion.",
                "La discorde est le plus grand mal du genre humain, et la tolérance en est le seul remède.",
                "Il n'y a point de hasard ; tout est épreuve, ou punition, ou récompense, ou prévoyance.",
                "Dieu n'a créé les femmes que pour apprivoiser les hommes.",
                "A la cour, mon fils, l'art le plus nécessaire N'est pas de bien parler, mais de savoir se taire.",
                "Le fanatisme est un monstre mille fois plus dangereux que l'athéisme philosophique.",
                "L'espèce humaine est la seule qui sache qu'elle doit mourir.",
                "Le malheur des uns fait le bonheur des autres.",
                "Nous naissons, nous vivons, bergère, Nous mourons sans savoir comment ; Chacun est parti du néant : Où va-t-il ? Dieu le sait, ma chère.",
                "Il vaut mieux hasarder de sauver un coupable que de condamner un innocent.",
                "Les injures atroces n'ont jamais fait de tort qu'à ceux qui les ont dites.",
                "La lecture agrandit l'âme, et un ami éclairé la console.",
                "Un courage indompté, dans le coeur des mortels, Fait ou les grands héros ou les grands criminels.",
                "Si Dieu n'existait pas, il faudrait l'inventer.",
                "La patrie est là où on vit heureux.",
                "La beauté plaît aux yeux, la douceur charme l'âme.",
                "Quiconque pense fait penser.",
                "Le doute est un état mental désagréable, mais la certitude est ridicule.",
                "Ce que nous appelons le hasard n'est et ne peut être que la cause ignorée d'un effet connu.",
                "La médisance est fille de l'amour-propre et de l'oisiveté.",
                "Par tout pays, la religion dominante, quand elle ne persécute point, engloutit à la longue toutes les autres.",
                "Aime la vérité, mais pardonne l'erreur.",
                "Il n'est point de grand conquérant qui ne soit grand politique. Un conquérant est un homme dont la tête se sert, avec une habileté heureuse, du bras d'autrui.",
                "La politique est l'art de mentir à propos.",
                "Les Incas avaient des palais incrustés d'or et couverts de paille : emblème de bien des gouvernements.",
                "Celui qui soutient sa folie par le meurtre, est un fanatique.",
                "Je meurs en adorant dieu, en aimant mes amis, en ne détestant pas mes ennemis, en haissant la superstition.",
                "Je ne suis pas d'accord avec ce que vous dites, mais je me battrai jusqu'au bout pour que vous puissiez le dire.",
                "C'est à celui qui domine sur les esprits par la force de la vérité, non à ceux qui font les esclaves par la violence, que nous devons nos respects.",
                "On a trouvé, en bonne politique, le secret de faire mourir de faim ceux qui, en cultivant la terre, font vivre les autres.",
                "Le premier pas, mon fils, que l'on fait dans le monde Est celui dont dépend le reste de nos jours.",
                "Si l'on n'est pas sensible, on n'est jamais sublime.",
                "Le bonheur est un mot abstrait composé de quelques idées de plaisir.",
                "Les hommes ne haïssent l'avare que parce qu'il n'y a rien à gagner avec lui.",
                "Un jour, tout sera bien, voilà notre espérance Tout est bien aujourd'hui, voilà l'illusion.",
                "Dieu nous a donné le vivre ; c'est à nous de nous donner le bien vivre.",
                "J'ai décidé d'être heureux parce que c'est bon pour la santé.",
                "J'ai décidé d'être heureux parce que c'est bon pour la santé.",
                "J'ai décidé d'être heureux parce que c'est bon pour la santé.",
                "Toute secte, en quelque genre que ce puisse être, est le ralliement du doute et de l'erreur.",
                "Toute secte, en quelque genre que ce puisse être, est le ralliement du doute et de l'erreur.",
                "Plus on a médité, plus on est en état d'affirmer qu'on ne sait rien.",
                "Le temps, qui seul fait la réputation des hommes, rend à la fin leurs défauts respectables.",
                "Les femmes ressemblent aux girouettes : elles se fixent quand elles se rouillent.",
                "Quoi point d'argent ? Et de l'ambition ! Pauvre imprudent ! Apprends qu'en ce royaume Tous les honneurs sont fondés sur le bien, Que rien n'est rien, que de rien ne vaut rien.",
                "Les hommes sont des insectes se dévorant les uns les autres sur un petit atome de boue.",
                "L'univers m'embarrasse et je ne puis songer que cette horloge existe et n'ait pas d'horloger.",
                "La politique a sa source dans la perversité plus que dans la grandeur de l'esprit humain.",
                "Toute plaisanterie doit être courte, et même le sérieux devrait bien être court aussi.",
                "Malheur aux détails, la postérité les néglige tous.",
                "Ce n'est pas l'amour qu'il fallait peindre aveugle, c'est l'amour-propre.",
                "En ouvrages de goût, en musique, en poésie, en peinture, c'est le goût qui tient lieu de montre ; et celui qui n'en juge que par des règles en juge mal.",
                "Toujours du plaisir n'est pas du plaisir.",
                "Jamais la nature n'est si avilie, que quand l'ignorance superstitieuse est armée du pouvoir.",
                "Plus les hommes seront éclairés, et plus ils seront libres.",
                "Rien n'empêche qu'on soit un bon juge, un brave guerrier, un homme d'Etat habile, quand on a eu un père bon calculateur.",
                "Et qui pardonne au crime en devient complice.",
                "Il a fallu des siècles pour rendre justice à l'humanité, pour sentir qu'il est horrible que le grand nombre semât et que le petit nombre recueillît.",
                "C'est assurément ne pas connaître le coeur humain que de penser qu'on peut le remuer par des fictions.",
                "Dieu ? Nous nous saluons, mais nous ne nous parlons pas.",
                "C'est l'amour de nous-mêmes qui assiste l'amour des autres ; c'est par nos besoins mutuels que nous sommes utiles au genre humain.",
                "Le peuple reçoit la religion, les lois, comme la monnaie, sans l'examiner.",
                "Les grandes choses sont souvent plus faciles qu'on ne pense.",
                "Puissent tous les hommes se souvenir qu'ils sont frères.",
                "Ce n'est pas que le suicide soit toujours de la folie. Mais en général, ce n'est pas dans un accès de raison que l'on se tue.",
                "Les bavards sont les plus discrets des hommes : ils parlent pour ne rien dire.",
                "Je compterais plus sur le rôle d'un homme espérant une grande récompense que sur celui d'un homme l'ayant reçue.",
                "Les hommes abreuvés de liqueurs fortes ont tous un sang aigri et adulte qui les rend fous en cent manières différentes.",
            ]
        },
    ]
};
let aleatoire = null;
let random = null;

$(document).ready(function () {

    $(".savedQuote").html(localStorage.getItem("citationSauvegarde"));
    $(".savedAuthor").html(localStorage.getItem("auteurSauvegarde"));

    random = Math.floor(Math.random() * citation.Citations.length);
    aleatoire = Math.floor(Math.random() * citation.Citations[random].hisCitations.length);

    let displayAuthor = $(".auteur");
    let displayQuote = $(".citation");
    displayQuote.html(citation.Citations[random].hisCitations[aleatoire]);
    displayAuthor.html(citation.Citations[random].Auteur);

    $("#generer").click(function () {
        random = Math.floor(Math.random() * citation.Citations.length);
        aleatoire = Math.floor(Math.random() * citation.Citations[random].hisCitations.length);
        $(".citation").html(citation.Citations[random].hisCitations[aleatoire]);
        $(".auteur").html(citation.Citations[random].Auteur);
    });

    $("#ranger").click(function () {
        localStorage.setItem("citationSauvegarde", displayQuote.html().valueOf()); //Mémo: Set l'item dans un array oui Objet puis afficher ledit Array/objet plutôt que la donné elle même
        localStorage.setItem("auteurSauvegarde", displayAuthor.html().valueOf());
        $(".savedQuote").html(localStorage.getItem("citationSauvegarde"));
        $(".savedAuthor").html(localStorage.getItem("auteurSauvegarde"));
        /*-------------------------------------------------------------------*/
        random = Math.floor(Math.random() * citation.Citations.length);
        aleatoire = Math.floor(Math.random() * citation.Citations[random].hisCitations.length);
        $(".citation").html(citation.Citations[random].hisCitations[aleatoire]);
        $(".auteur").html(citation.Citations[random].Auteur);
    });

    $("#cleaner").click(function () {
        localStorage.clear();
        $(".savedQuote").html(localStorage.getItem("citationSauvegarde"));
        $(".savedAuthor").html(localStorage.getItem("auteurSauvegarde"));
    });
});